# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activerecord-postgres-earthdistance}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Juan Maiz"]
  s.date = %q{2011-02-24}
  s.description = %q{I'll write it tomorrow}
  s.email = %q{juanmaiz@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/activerecord-postgres-earthdistance.rb",
     "test/test_activerecord-postgres-earthdistance.rb"
  ]
  s.homepage = %q{http://github.com/softa/activerecord-postgres-earthdistance}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Now you can filter records within a radius}
  s.test_files = [
    "spec/activerecord-postgres-hstore_spec.rb",
     "spec/spec_helper.rb",
     "test/test_activerecord-postgres-earthdistance.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

