# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activerecord-postgres-earthdistance}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Juan Maiz", "Diogo Biazus"]
  s.date = %q{2011-06-23}
  s.description = %q{I'll write it tomorrow}
  s.email = %q{diogob@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "activerecord-postgres-earthdistance.gemspec",
    "lib/activerecord-postgres-earthdistance.rb",
    "lib/activerecord-postgres-earthdistance/activerecord.rb",
    "lib/templates/cube.sql",
    "lib/templates/earthdistance.sql",
    "lib/templates/setup_earthdistance.rb",
    "test/app/.gitignore",
    "test/app/Gemfile",
    "test/app/Gemfile.lock",
    "test/app/README",
    "test/app/Rakefile",
    "test/app/app/controllers/application_controller.rb",
    "test/app/app/helpers/application_helper.rb",
    "test/app/app/models/place.rb",
    "test/app/app/views/layouts/application.html.erb",
    "test/app/config.ru",
    "test/app/config/application.rb",
    "test/app/config/boot.rb",
    "test/app/config/database.yml",
    "test/app/config/environment.rb",
    "test/app/config/environments/development.rb",
    "test/app/config/environments/production.rb",
    "test/app/config/environments/test.rb",
    "test/app/config/initializers/backtrace_silencers.rb",
    "test/app/config/initializers/inflections.rb",
    "test/app/config/initializers/mime_types.rb",
    "test/app/config/initializers/secret_token.rb",
    "test/app/config/initializers/session_store.rb",
    "test/app/config/initializers/use_sql_schema.rb",
    "test/app/config/locales/en.yml",
    "test/app/config/routes.rb",
    "test/app/db/development_structure.sql",
    "test/app/db/migrate/20110225205046_setup_earthdistance.rb",
    "test/app/db/migrate/20110225205131_create_places.rb",
    "test/app/db/schema.rb",
    "test/app/db/seeds.rb",
    "test/app/doc/README_FOR_APP",
    "test/app/lib/tasks/.gitkeep",
    "test/app/public/404.html",
    "test/app/public/422.html",
    "test/app/public/500.html",
    "test/app/public/favicon.ico",
    "test/app/public/images/rails.png",
    "test/app/public/index.html",
    "test/app/public/javascripts/application.js",
    "test/app/public/javascripts/controls.js",
    "test/app/public/javascripts/dragdrop.js",
    "test/app/public/javascripts/effects.js",
    "test/app/public/javascripts/prototype.js",
    "test/app/public/javascripts/rails.js",
    "test/app/public/robots.txt",
    "test/app/public/stylesheets/.gitkeep",
    "test/app/script/rails",
    "test/app/test/performance/browsing_test.rb",
    "test/app/test/test_helper.rb",
    "test/app/test/unit/place_test.rb",
    "test/app/vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/softa/activerecord-postgres-earthdistance}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Now you can filter records within a radius}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<pg>, [">= 0.11"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<pg>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<pg>, [">= 0.11"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<pg>, [">= 0.11"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
  end
end

